import type { BusinessCase } from '../../types/businessCase';
import { FieldSuggestions } from '../FieldSuggestions';
import { fieldSuggestions } from '../../data/exampleData';

interface SecurityComplianceProps {
  formData: BusinessCase;
  updateField: (field: keyof BusinessCase, value: string) => void;
}

export function SecurityCompliance({ formData, updateField }: SecurityComplianceProps) {
  return (
    <div className="space-y-5">
      <div>
        <h3 className="text-lg font-semibold text-gray-800 mb-3">Security & Compliance</h3>
        <p className="text-sm text-gray-600 mb-4">Define security, privacy, and compliance requirements</p>
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          Compliance Standards
        </label>
        <textarea
          value={formData.compliance_standards}
          onChange={(e) => updateField('compliance_standards', e.target.value)}
          className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          rows={2}
          placeholder="e.g., GDPR, HIPAA, ISO 27001, SOC 2..."
        />
        <FieldSuggestions suggestions={fieldSuggestions.compliance_standards || []} />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          Authentication & Encryption Requirements
        </label>
        <textarea
          value={formData.authentication_encryption}
          onChange={(e) => updateField('authentication_encryption', e.target.value)}
          className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          rows={2}
          placeholder="Required level of device authentication and encryption..."
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          Data Ownership
        </label>
        <input
          type="text"
          value={formData.data_ownership}
          onChange={(e) => updateField('data_ownership', e.target.value)}
          className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          placeholder="Who owns the data generated by the devices?"
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          Security Risks & Concerns
        </label>
        <textarea
          value={formData.security_risks}
          onChange={(e) => updateField('security_risks', e.target.value)}
          className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          rows={2}
          placeholder="What are the risks if the system is compromised?"
        />
      </div>
    </div>
  );
}
