/*
  # Add Comprehensive Project Information Fields

  ## Overview
  This migration extends the business_cases table to capture detailed project information across four key areas:
  1. Problem Description - Business Context
  2. Technical Requirements - System Specifications
  3. Project Requirements - Delivery Framework
  4. Strategic Considerations - Long-term Planning

  ## Changes to Tables

  ### `business_cases` - New Columns Added

  #### 1. Problem Description - Business Understanding
  - `business_outcomes` (text) - Expected business outcomes (cost reduction, revenue, safety)
  - `stakeholders` (text) - Key stakeholders and end-users
  - `success_metrics` (text) - KPIs for project success
  - `current_process` (text) - Current process and pain points
  - `market_drivers` (text) - Market or regulatory drivers
  - `expected_benefits` (text) - Short-term and long-term benefits
  
  #### 1. Problem Description - Operational Context
  - `operating_environment` (text) - Environment description (factory, city, logistics, etc.)
  - `scale_details` (text) - Number of sites, devices, assets, users
  - `environmental_conditions` (text) - Physical conditions (temperature, humidity, distance, mobility)
  - `asset_mobility` (text) - Frequency of device/asset movement or location changes
  - `maintenance_ownership` (text) - Who will manage and maintain the system

  #### 2. Technical Requirements - Devices & Edge
  - `device_types` (text) - Types of things to connect (sensors, actuators, gateways, vehicles, machines)
  - `data_collection_specs` (text) - Data type, frequency, format, precision
  - `transmission_frequency` (text) - How often data should be transmitted
  - `real_time_needs` (text) - Latency or real-time processing requirements
  - `edge_intelligence` (text) - Level of device intelligence or edge computing needed
  - `power_constraints` (text) - Power constraints (battery, mains, energy harvesting)
  - `device_management` (text) - Device provisioning, OTA updates, remote management

  #### 2. Technical Requirements - Connectivity
  - `network_technologies` (text) - Available or preferred network tech (Wi-Fi, LTE/5G, LoRaWAN, Zigbee, Ethernet, satellite)
  - `coverage_limitations` (text) - Coverage or bandwidth limitations
  - `data_per_device` (text) - Data transmitted per device per day
  - `throughput_needs` (text) - Expected data throughput, latency, and availability needs
  - `connectivity_scope` (text) - Roaming or global connectivity requirements

  #### 2. Technical Requirements - Cloud & Data Platform
  - `data_location` (text) - Where data will be stored and processed (cloud, on-prem, hybrid)
  - `analytics_capabilities` (text) - Required analytics or AI capabilities (real-time, predictive, batch)
  - `enterprise_integration` (text) - Integration with existing systems (ERP, CRM, SCADA)
  - `api_requirements` (text) - Expected APIs or data exchange mechanisms
  - `data_retention` (text) - Data retention and archival policies

  #### 2. Technical Requirements - Security & Compliance
  - `compliance_standards` (text) - Applicable standards (GDPR, HIPAA, ISO 27001)
  - `authentication_encryption` (text) - Required level of device authentication and encryption
  - `data_ownership` (text) - Who owns the data generated by devices
  - `security_risks` (text) - Risks if the system is compromised

  #### 2. Technical Requirements - Scalability & Performance
  - `device_growth` (text) - Devices needed now and in the future
  - `data_growth_rate` (text) - Expected data growth rate
  - `firmware_management` (text) - How to handle firmware upgrades and version management

  #### 3. Project Requirements - Schedule & Milestones
  - `project_timeline` (text) - Target timeline for MVP, pilot, and full deployment
  - `critical_milestones` (text) - Critical milestones or external dependencies

  #### 3. Project Requirements - Budget & ROI
  - `budget_details` (text) - Available budget (CAPEX/OPEX)
  - `expected_roi` (text) - Expected ROI or payback period
  - `cost_constraints` (text) - Cost constraints on devices, connectivity, or cloud services

  #### 3. Project Requirements - Team & Governance
  - `solution_ownership` (text) - Who will own the solution after deployment (internal IT, operations, external MSP)
  - `required_roles` (text) - Required roles (hardware, firmware, cloud, data analytics, UX)
  - `existing_vendors` (text) - Existing vendors or technology partners to align with

  #### 3. Project Requirements - Regulatory & Certification
  - `device_certifications` (text) - Certification needs for devices (CE, FCC, UL, ATEX)
  - `geographic_compliance` (text) - Geographic compliance constraints (data localization, telecom regulation)

  #### 4. Strategic Considerations - Sustainability & Lifecycle
  - `solution_lifetime` (text) - How long the solution must operate and expected device lifetime
  - `maintenance_plan` (text) - Plan for maintenance, updates, and decommissioning
  - `sustainability_goals` (text) - Environmental or sustainability goals (low power, recyclability)

  #### 4. Strategic Considerations - Vendor & Technology Strategy
  - `build_vs_buy` (text) - Which parts of the solution will be custom vs off-the-shelf
  - `platform_preferences` (text) - Preferred cloud or IoT platforms
  - `vendor_lockin_tolerance` (text) - Is vendor lock-in acceptable or should architecture be portable

  #### 4. Strategic Considerations - Data Strategy
  - `data_access_rights` (text) - Who can access or monetize the data
  - `analytics_plan` (text) - Plan for analytics, dashboards, or machine learning
  - `interoperability_needs` (text) - Interoperability needs (open standards, MQTT, OPC-UA)

  #### 4. Strategic Considerations - Risk & Contingency
  - `connectivity_failure_plan` (text) - What happens if connectivity is lost
  - `critical_failure_scenarios` (text) - Critical failure scenarios
  - `incident_response` (text) - Cybersecurity incident response plans

  ## Notes
  - All new fields are optional (no NOT NULL constraint) to maintain backward compatibility
  - Existing business cases will have NULL values for these fields
  - Default empty strings for better UX in forms
*/

-- Add Problem Description - Business Understanding fields
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'business_outcomes') THEN
    ALTER TABLE business_cases ADD COLUMN business_outcomes text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'stakeholders') THEN
    ALTER TABLE business_cases ADD COLUMN stakeholders text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'success_metrics') THEN
    ALTER TABLE business_cases ADD COLUMN success_metrics text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'current_process') THEN
    ALTER TABLE business_cases ADD COLUMN current_process text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'market_drivers') THEN
    ALTER TABLE business_cases ADD COLUMN market_drivers text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'expected_benefits') THEN
    ALTER TABLE business_cases ADD COLUMN expected_benefits text DEFAULT '';
  END IF;
END $$;

-- Add Problem Description - Operational Context fields
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'operating_environment') THEN
    ALTER TABLE business_cases ADD COLUMN operating_environment text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'scale_details') THEN
    ALTER TABLE business_cases ADD COLUMN scale_details text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'environmental_conditions') THEN
    ALTER TABLE business_cases ADD COLUMN environmental_conditions text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'asset_mobility') THEN
    ALTER TABLE business_cases ADD COLUMN asset_mobility text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'maintenance_ownership') THEN
    ALTER TABLE business_cases ADD COLUMN maintenance_ownership text DEFAULT '';
  END IF;
END $$;

-- Add Technical Requirements - Devices & Edge fields
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'device_types') THEN
    ALTER TABLE business_cases ADD COLUMN device_types text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'data_collection_specs') THEN
    ALTER TABLE business_cases ADD COLUMN data_collection_specs text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'transmission_frequency') THEN
    ALTER TABLE business_cases ADD COLUMN transmission_frequency text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'real_time_needs') THEN
    ALTER TABLE business_cases ADD COLUMN real_time_needs text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'edge_intelligence') THEN
    ALTER TABLE business_cases ADD COLUMN edge_intelligence text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'power_constraints') THEN
    ALTER TABLE business_cases ADD COLUMN power_constraints text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'device_management') THEN
    ALTER TABLE business_cases ADD COLUMN device_management text DEFAULT '';
  END IF;
END $$;

-- Add Technical Requirements - Connectivity fields
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'network_technologies') THEN
    ALTER TABLE business_cases ADD COLUMN network_technologies text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'coverage_limitations') THEN
    ALTER TABLE business_cases ADD COLUMN coverage_limitations text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'data_per_device') THEN
    ALTER TABLE business_cases ADD COLUMN data_per_device text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'throughput_needs') THEN
    ALTER TABLE business_cases ADD COLUMN throughput_needs text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'connectivity_scope') THEN
    ALTER TABLE business_cases ADD COLUMN connectivity_scope text DEFAULT '';
  END IF;
END $$;

-- Add Technical Requirements - Cloud & Data Platform fields
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'data_location') THEN
    ALTER TABLE business_cases ADD COLUMN data_location text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'analytics_capabilities') THEN
    ALTER TABLE business_cases ADD COLUMN analytics_capabilities text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'enterprise_integration') THEN
    ALTER TABLE business_cases ADD COLUMN enterprise_integration text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'api_requirements') THEN
    ALTER TABLE business_cases ADD COLUMN api_requirements text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'data_retention') THEN
    ALTER TABLE business_cases ADD COLUMN data_retention text DEFAULT '';
  END IF;
END $$;

-- Add Technical Requirements - Security & Compliance fields
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'compliance_standards') THEN
    ALTER TABLE business_cases ADD COLUMN compliance_standards text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'authentication_encryption') THEN
    ALTER TABLE business_cases ADD COLUMN authentication_encryption text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'data_ownership') THEN
    ALTER TABLE business_cases ADD COLUMN data_ownership text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'security_risks') THEN
    ALTER TABLE business_cases ADD COLUMN security_risks text DEFAULT '';
  END IF;
END $$;

-- Add Technical Requirements - Scalability & Performance fields
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'device_growth') THEN
    ALTER TABLE business_cases ADD COLUMN device_growth text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'data_growth_rate') THEN
    ALTER TABLE business_cases ADD COLUMN data_growth_rate text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'firmware_management') THEN
    ALTER TABLE business_cases ADD COLUMN firmware_management text DEFAULT '';
  END IF;
END $$;

-- Add Project Requirements - Schedule & Milestones fields
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'project_timeline') THEN
    ALTER TABLE business_cases ADD COLUMN project_timeline text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'critical_milestones') THEN
    ALTER TABLE business_cases ADD COLUMN critical_milestones text DEFAULT '';
  END IF;
END $$;

-- Add Project Requirements - Budget & ROI fields
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'budget_details') THEN
    ALTER TABLE business_cases ADD COLUMN budget_details text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'expected_roi') THEN
    ALTER TABLE business_cases ADD COLUMN expected_roi text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'cost_constraints') THEN
    ALTER TABLE business_cases ADD COLUMN cost_constraints text DEFAULT '';
  END IF;
END $$;

-- Add Project Requirements - Team & Governance fields
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'solution_ownership') THEN
    ALTER TABLE business_cases ADD COLUMN solution_ownership text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'required_roles') THEN
    ALTER TABLE business_cases ADD COLUMN required_roles text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'existing_vendors') THEN
    ALTER TABLE business_cases ADD COLUMN existing_vendors text DEFAULT '';
  END IF;
END $$;

-- Add Project Requirements - Regulatory & Certification fields
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'device_certifications') THEN
    ALTER TABLE business_cases ADD COLUMN device_certifications text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'geographic_compliance') THEN
    ALTER TABLE business_cases ADD COLUMN geographic_compliance text DEFAULT '';
  END IF;
END $$;

-- Add Strategic Considerations - Sustainability & Lifecycle fields
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'solution_lifetime') THEN
    ALTER TABLE business_cases ADD COLUMN solution_lifetime text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'maintenance_plan') THEN
    ALTER TABLE business_cases ADD COLUMN maintenance_plan text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'sustainability_goals') THEN
    ALTER TABLE business_cases ADD COLUMN sustainability_goals text DEFAULT '';
  END IF;
END $$;

-- Add Strategic Considerations - Vendor & Technology Strategy fields
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'build_vs_buy') THEN
    ALTER TABLE business_cases ADD COLUMN build_vs_buy text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'platform_preferences') THEN
    ALTER TABLE business_cases ADD COLUMN platform_preferences text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'vendor_lockin_tolerance') THEN
    ALTER TABLE business_cases ADD COLUMN vendor_lockin_tolerance text DEFAULT '';
  END IF;
END $$;

-- Add Strategic Considerations - Data Strategy fields
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'data_access_rights') THEN
    ALTER TABLE business_cases ADD COLUMN data_access_rights text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'analytics_plan') THEN
    ALTER TABLE business_cases ADD COLUMN analytics_plan text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'interoperability_needs') THEN
    ALTER TABLE business_cases ADD COLUMN interoperability_needs text DEFAULT '';
  END IF;
END $$;

-- Add Strategic Considerations - Risk & Contingency fields
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'connectivity_failure_plan') THEN
    ALTER TABLE business_cases ADD COLUMN connectivity_failure_plan text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'critical_failure_scenarios') THEN
    ALTER TABLE business_cases ADD COLUMN critical_failure_scenarios text DEFAULT '';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'business_cases' AND column_name = 'incident_response') THEN
    ALTER TABLE business_cases ADD COLUMN incident_response text DEFAULT '';
  END IF;
END $$;